# SQLite version 3.x
#   gem install sqlite3-ruby (not necessary on OS X Leopard)
development:
  adapter: mysql
  database: legisdados
  username: root
  host: localhost
  password: 
  pool: 10
  timeout: 5000

test:
  adapter: mysql
  database: pdata_test
  username: root
  password: ''
  pool: 10
  timeout: 5000

production:
  adapter: mysql
  database: legisdados_production
  username: legisdados
  host: localhost
  password: lo9ki8
  pool: 10
  timeout: 5000